name: sample-xcode-actions
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show Xcode Version 
        run: xcodebuild -version 

      - name: Build project 
        run: |
		    xcodebuild -project XCtestSample.xcodeproj -target XCtestSample -sdk iphonesimulator -configuration Debug build 

